# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushers', '0002_rollsday'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollsday',
            name='activePushers',
            field=models.ManyToManyField(to='pushers.Pusher'),
        ),
        migrations.AlterField(
            model_name='rollsday',
            name='date',
            field=models.DateField(),
        ),
    ]
