# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushers', '0003_auto_20161112_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rollsday',
            old_name='activePushers',
            new_name='active_pushers',
        ),
    ]
