# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushers', '0004_auto_20161112_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buggy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
