# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushers', '0005_buggy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuggyRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buggy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushers.Buggy')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushers.RollsDay')),
            ],
        ),
        migrations.CreateModel(
            name='RollHill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pusher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushers.Pusher')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushers.BuggyRoll')),
            ],
        ),
        migrations.AddField(
            model_name='buggyroll',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushers.Roll'),
        ),
    ]
