# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushers', '0006_auto_20161113_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollhill',
            name='hill',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
